### ISSUE TITLE
[Bug Report] Creepers

### ISSUE THREAD

**Issue by YvaltasKitty** [Aaron2550/Avalon-Shattered-Future#4]
**Describe the bug**
Creepers spawn in many areas, such as the crypt, although this may be unintended. They also sometimes walk into towns with explosions off. I have noticed that when they explode in an explosion protected area, they do not do anything, but when they explode anywhere else, they blow up blocks and deal damage, plus drop a lingering potion that does more damage. This seems unintended, since lingering potions are normally used as a way to balance creepers in grief protected areas.

**To Reproduce**
Bait a creeper into blowing up both inside of spawn and in an unclaimed area in the wild.

**Expected behavior**
The creeper in spawn will likely have no noticeable effect on anything, while the other creeper will both break blocks and drop a lingering potion.

**Comment by Aaron2550** [comment]
we'll have to look into the plugin that adds the lingering potion and see if the potion is disable-able for regions since i dont think we should enable explosions at spawn...

**Comment by YvaltasKitty** [comment]
Update: Have not seen this happen again since. Possibly a one-time or similarly rare occurrence, will update if I see it happen again.
