### ISSUE TITLE
[Suggestion] Custom Food

### ISSUE THREAD

**Issue by YvaltasKitty** [Aaron2550/Avalon-Shattered-Future#8]
**Is your feature request related to a problem? Please describe.**
Hunger from custom food goes down quickly enough that I suspect it does not fill the player's saturation bar.

**Describe the solution you'd like**
Have the custom food give a saturation amount based on how much hunger it refills.

**Additional context**
Steak, for example, gives 8 hunger and 12.8 saturation. This would be a good proportion to use for custom food as well.

**Comment by Aaron2550** [comment]
I'm not sure but, when I made a food item it asked me for saturation specifically. Maybe some admins missed it? I could look into this when I'm back home in about 10 to 11 hours

**Comment by YvaltasKitty** [comment]
It is also possible that the amount of saturation per food item is just heavily out of proportion with the amount of food provided, such as an item that gives 8 hunger and 4 saturation.

**Comment by Aaron2550** [comment]
Couldn't do it today because of downtime, sry. If I'll remember I'll do it tomorrow

**Comment by Aaron2550** [comment]
fixed
